-- PostgreSQL schema setup for MLB Stats
-- Creates tables in both public and fantasy schemas

CREATE SCHEMA IF NOT EXISTS fantasy;

-- games
CREATE TABLE IF NOT EXISTS public.games (
    id INTEGER PRIMARY KEY,
    game_guid TEXT,
    feed_link TEXT,
    game_type TEXT,
    season INTEGER,
    game_date TIMESTAMP,
    official_date DATE,
    away_team TEXT,
    away_team_id INTEGER,
    away_team_score INTEGER,
    away_team_total_wins INTEGER,
    away_team_total_losses INTEGER,
    away_team_series_number INTEGER,
    home_team TEXT,
    home_team_id INTEGER,
    home_team_score INTEGER,
    home_team_total_wins INTEGER,
    home_team_total_losses INTEGER,
    home_team_series_number INTEGER,
    number_of_games_in_series INTEGER,
    series_game_number INTEGER,
    venue_name TEXT,
    venue_id INTEGER
);

-- teams
CREATE TABLE IF NOT EXISTS public.teams (
    id INTEGER PRIMARY KEY,
    name TEXT,
    venue_id INTEGER,
    venue_name TEXT,
    league_id INTEGER,
    league_name TEXT
);

-- team_boxscores_home_batting
CREATE TABLE IF NOT EXISTS public.team_boxscores_home_batting (
    game_id INTEGER PRIMARY KEY,
    season INTEGER,
    home_team TEXT,
    home_team_id INTEGER,
    league TEXT,
    league_id INTEGER,
    division TEXT,
    division_id INTEGER,
    home_team_wins INTEGER,
    home_team_losses INTEGER,
    home_team_batting_flyouts INTEGER,
    home_team_batting_groundouts INTEGER,
    home_team_batting_airouts INTEGER,
    home_team_batting_runs INTEGER,
    home_team_batting_singles INTEGER,
    home_team_batting_doubles INTEGER,
    home_team_batting_triples INTEGER,
    home_team_batting_homeruns INTEGER,
    home_team_batting_hits INTEGER,
    home_team_batting_strikeouts INTEGER,
    home_team_batting_walks INTEGER,
    home_team_batting_int_walks INTEGER,
    home_team_batting_hbp INTEGER,
    home_team_batting_avg NUMERIC(6,3),
    home_team_batting_at_bats INTEGER,
    home_team_batting_obp NUMERIC(6,3),
    home_team_batting_slg NUMERIC(6,3),
    home_team_batting_ops NUMERIC(6,3),
    home_team_batting_caught_stealing INTEGER,
    home_team_batting_stolen_bases INTEGER,
    home_team_batting_gidp INTEGER,
    home_team_batting_gitp INTEGER,
    home_team_batting_plate_appearances INTEGER,
    home_team_batting_total_bases INTEGER,
    home_team_batting_rbi INTEGER,
    home_team_batting_lob INTEGER,
    home_team_batting_sac_bunts INTEGER,
    home_team_batting_sac_flies INTEGER,
    home_team_batting_catcher_int INTEGER,
    home_team_batting_pickoffs INTEGER,
    home_team_batting_popouts INTEGER,
    home_team_batting_lineouts INTEGER
);

-- team_boxscores_away_batting
CREATE TABLE IF NOT EXISTS public.team_boxscores_away_batting (
    game_id INTEGER PRIMARY KEY,
    season INTEGER,
    away_team TEXT,
    away_team_id INTEGER,
    league TEXT,
    league_id INTEGER,
    division TEXT,
    division_id INTEGER,
    away_team_wins INTEGER,
    away_team_losses INTEGER,
    away_team_batting_flyouts INTEGER,
    away_team_batting_groundouts INTEGER,
    away_team_batting_airouts INTEGER,
    away_team_batting_runs INTEGER,
    away_team_batting_singles INTEGER,
    away_team_batting_doubles INTEGER,
    away_team_batting_triples INTEGER,
    away_team_batting_homeruns INTEGER,
    away_team_batting_hits INTEGER,
    away_team_batting_strikeouts INTEGER,
    away_team_batting_walks INTEGER,
    away_team_batting_int_walks INTEGER,
    away_team_batting_hbp INTEGER,
    away_team_batting_avg NUMERIC(6,3),
    away_team_batting_at_bats INTEGER,
    away_team_batting_obp NUMERIC(6,3),
    away_team_batting_slg NUMERIC(6,3),
    away_team_batting_ops NUMERIC(6,3),
    away_team_batting_caught_stealing INTEGER,
    away_team_batting_stolen_bases INTEGER,
    away_team_batting_gidp INTEGER,
    away_team_batting_gitp INTEGER,
    away_team_batting_plate_appearances INTEGER,
    away_team_batting_total_bases INTEGER,
    away_team_batting_rbi INTEGER,
    away_team_batting_lob INTEGER,
    away_team_batting_sac_bunts INTEGER,
    away_team_batting_sac_flies INTEGER,
    away_team_batting_catcher_int INTEGER,
    away_team_batting_pickoffs INTEGER,
    away_team_batting_popouts INTEGER,
    away_team_batting_lineouts INTEGER
);

-- team_boxscores_home_pitching_and_fielding
CREATE TABLE IF NOT EXISTS public.team_boxscores_home_pitching_and_fielding (
    game_id INTEGER PRIMARY KEY,
    season INTEGER,
    home_team TEXT,
    home_team_id INTEGER,
    league TEXT,
    league_id INTEGER,
    division TEXT,
    division_id INTEGER,
    home_team_wins INTEGER,
    home_team_losses INTEGER,
    home_team_pitching_flyouts INTEGER,
    home_team_pitching_groundouts INTEGER,
    home_team_pitching_airouts INTEGER,
    home_team_pitching_runs INTEGER,
    home_team_pitching_singles INTEGER,
    home_team_pitching_doubles INTEGER,
    home_team_pitching_triples INTEGER,
    home_team_pitching_homeruns INTEGER,
    home_team_pitching_hits INTEGER,
    home_team_pitching_strikeouts INTEGER,
    home_team_pitching_walks INTEGER,
    home_team_pitching_int_walks INTEGER,
    home_team_pitching_hbp INTEGER,
    home_team_pitching_baa NUMERIC(6,3),
    home_team_pitching_at_bats INTEGER,
    home_team_pitching_obp NUMERIC(6,3),
    home_team_pitching_slg NUMERIC(6,3),
    home_team_pitching_ops NUMERIC(6,3),
    home_team_pitching_caught_stealing INTEGER,
    home_team_pitching_stolen_bases INTEGER,
    home_team_pitching_era NUMERIC(6,3),
    home_team_pitching_ip NUMERIC(5,1),
    home_team_pitching_save_opportunities INTEGER,
    home_team_pitching_earned_runs INTEGER,
    home_team_pitching_whip NUMERIC(6,3),
    home_team_pitching_batters_faced INTEGER,
    home_team_pitching_outs INTEGER,
    home_team_pitching_cg INTEGER,
    home_team_pitching_shutouts INTEGER,
    home_team_pitching_num_pitches INTEGER,
    home_team_pitching_balls INTEGER,
    home_team_pitching_strikes INTEGER,
    home_team_pitching_strike_perc NUMERIC(6,3),
    home_team_pitching_balks INTEGER,
    home_team_pitching_wild_pitches INTEGER,
    home_team_pitching_pickoffs INTEGER,
    home_team_pitching_groundouts_to_airouts NUMERIC(6,3),
    home_team_pitching_rbi INTEGER,
    home_team_pitching_pitches_per_inning NUMERIC(6,3),
    home_team_pitching_runs_scored_per_9 NUMERIC(6,3),
    home_team_pitching_homeruns_per_9 NUMERIC(6,3),
    home_team_pitching_inherited_runners INTEGER,
    home_team_pitching_inherited_runners_scored INTEGER,
    home_team_pitching_catcher_int INTEGER,
    home_team_pitching_gidp INTEGER,
    home_team_pitching_gitp INTEGER,
    home_team_pitching_plate_appearances INTEGER,
    home_team_pitching_total_bases INTEGER,
    home_team_pitching_lob INTEGER,
    home_team_pitching_sac_bunts INTEGER,
    home_team_pitching_sac_flies INTEGER,
    home_team_pitching_passed_ball INTEGER,
    home_team_pitching_popouts INTEGER,
    home_team_pitching_lineouts INTEGER,
    home_team_fielding_assists INTEGER,
    home_team_fielding_putouts INTEGER,
    home_team_fielding_errors INTEGER,
    home_team_fielding_chances INTEGER
);

-- team_boxscores_away_pitching_and_fielding
CREATE TABLE IF NOT EXISTS public.team_boxscores_away_pitching_and_fielding (
    game_id INTEGER PRIMARY KEY,
    season INTEGER,
    away_team TEXT,
    away_team_id INTEGER,
    league TEXT,
    league_id INTEGER,
    division TEXT,
    division_id INTEGER,
    away_team_wins INTEGER,
    away_team_losses INTEGER,
    away_team_pitching_flyouts INTEGER,
    away_team_pitching_groundouts INTEGER,
    away_team_pitching_airouts INTEGER,
    away_team_pitching_runs INTEGER,
    away_team_pitching_singles INTEGER,
    away_team_pitching_doubles INTEGER,
    away_team_pitching_triples INTEGER,
    away_team_pitching_homeruns INTEGER,
    away_team_pitching_hits INTEGER,
    away_team_pitching_strikeouts INTEGER,
    away_team_pitching_walks INTEGER,
    away_team_pitching_int_walks INTEGER,
    away_team_pitching_hbp INTEGER,
    away_team_pitching_baa NUMERIC(6,3),
    away_team_pitching_at_bats INTEGER,
    away_team_pitching_obp NUMERIC(6,3),
    away_team_pitching_slg NUMERIC(6,3),
    away_team_pitching_ops NUMERIC(6,3),
    away_team_pitching_caught_stealing INTEGER,
    away_team_pitching_stolen_bases INTEGER,
    away_team_pitching_era NUMERIC(6,3),
    away_team_pitching_ip NUMERIC(5,1),
    away_team_pitching_save_opportunities INTEGER,
    away_team_pitching_earned_runs INTEGER,
    away_team_pitching_whip NUMERIC(6,3),
    away_team_pitching_batters_faced INTEGER,
    away_team_pitching_outs INTEGER,
    away_team_pitching_cg INTEGER,
    away_team_pitching_shutouts INTEGER,
    away_team_pitching_num_pitches INTEGER,
    away_team_pitching_balls INTEGER,
    away_team_pitching_strikes INTEGER,
    away_team_pitching_strike_perc NUMERIC(6,3),
    away_team_pitching_balks INTEGER,
    away_team_pitching_wild_pitches INTEGER,
    away_team_pitching_pickoffs INTEGER,
    away_team_pitching_groundouts_to_airouts NUMERIC(6,3),
    away_team_pitching_rbi INTEGER,
    away_team_pitching_pitches_per_inning NUMERIC(6,3),
    away_team_pitching_runs_scored_per_9 NUMERIC(6,3),
    away_team_pitching_homeruns_per_9 NUMERIC(6,3),
    away_team_pitching_inherited_runners INTEGER,
    away_team_pitching_inherited_runners_scored INTEGER,
    away_team_pitching_catcher_int INTEGER,
    away_team_pitching_gidp INTEGER,
    away_team_pitching_gitp INTEGER,
    away_team_pitching_plate_appearances INTEGER,
    away_team_pitching_total_bases INTEGER,
    away_team_pitching_lob INTEGER,
    away_team_pitching_sac_bunts INTEGER,
    away_team_pitching_sac_flies INTEGER,
    away_team_pitching_passed_ball INTEGER,
    away_team_pitching_popouts INTEGER,
    away_team_pitching_lineouts INTEGER,
    away_team_fielding_assists INTEGER,
    away_team_fielding_putouts INTEGER,
    away_team_fielding_errors INTEGER,
    away_team_fielding_chances INTEGER
);

-- player_batting
CREATE TABLE IF NOT EXISTS public.player_batting (
    id TEXT PRIMARY KEY,
    player_id INTEGER,
    game_id INTEGER,
    name TEXT,
    link TEXT,
    position_name TEXT,
    position_type TEXT,
    team_id INTEGER,
    batting_order TEXT,
    flyouts INTEGER,
    groundouts INTEGER,
    airouts INTEGER,
    runs INTEGER,
    rbi INTEGER,
    singles INTEGER,
    doubles INTEGER,
    triples INTEGER,
    homeruns INTEGER,
    strikeouts INTEGER,
    walks INTEGER,
    intentional_walks INTEGER,
    hits INTEGER,
    hbp INTEGER,
    at_bats INTEGER,
    plate_appearances INTEGER,
    avg NUMERIC(6,3),
    obp NUMERIC(6,3),
    slg NUMERIC(6,3),
    ops NUMERIC(6,3),
    caught_stealing INTEGER,
    stolen_bases INTEGER,
    gidp INTEGER,
    gitp INTEGER,
    total_bases INTEGER,
    lob INTEGER,
    sac_bunts INTEGER,
    sac_flies INTEGER,
    catchers_int INTEGER,
    pickoffs INTEGER,
    popouts INTEGER,
    lineouts INTEGER
);

-- player_pitching
CREATE TABLE IF NOT EXISTS public.player_pitching (
    id TEXT PRIMARY KEY,
    player_id INTEGER,
    game_id INTEGER,
    name TEXT,
    link TEXT,
    position_name TEXT,
    position_type TEXT,
    team_id INTEGER,
    starts INTEGER,
    appearances INTEGER,
    flyouts INTEGER,
    groundouts INTEGER,
    airouts INTEGER,
    runs INTEGER,
    rbi INTEGER,
    singles INTEGER,
    doubles INTEGER,
    triples INTEGER,
    homeruns INTEGER,
    strikeouts INTEGER,
    walks INTEGER,
    intentional_walks INTEGER,
    hits INTEGER,
    hbp INTEGER,
    at_bats INTEGER,
    avg NUMERIC(6,3),
    obp NUMERIC(6,3),
    slg NUMERIC(6,3),
    ops NUMERIC(6,3),
    caught_stealing INTEGER,
    stolen_bases INTEGER,
    ip NUMERIC(5,1),
    wins INTEGER,
    losses INTEGER,
    saves INTEGER,
    save_opportunities INTEGER,
    holds INTEGER,
    blown_saves INTEGER,
    earned_runs INTEGER,
    batters_faced INTEGER,
    outs INTEGER,
    complete_games INTEGER,
    shutouts INTEGER,
    pitch_count INTEGER,
    balls INTEGER,
    strikes INTEGER,
    balks INTEGER,
    wild_pitches INTEGER,
    pickoffs INTEGER,
    runs_per_9 NUMERIC(6,3),
    homeruns_per_9 NUMERIC(6,3),
    inherited_runners INTEGER,
    inherited_runners_scored INTEGER,
    catchers_int INTEGER,
    sac_bunts INTEGER,
    sac_flies INTEGER,
    passed_ball INTEGER,
    popouts INTEGER,
    lineouts INTEGER
);

-- player_fielding
CREATE TABLE IF NOT EXISTS public.player_fielding (
    id TEXT PRIMARY KEY,
    player_id INTEGER,
    game_id INTEGER,
    name TEXT,
    link TEXT,
    position_name TEXT,
    position_type TEXT,
    team_id INTEGER,
    fielding_caught_stealing INTEGER,
    fielding_sb INTEGER,
    assists INTEGER,
    putouts INTEGER,
    errors INTEGER,
    chances INTEGER,
    fielding NUMERIC(6,3),
    fielding_passed_ball INTEGER,
    fielding_pickoffs INTEGER
);

-- Create fantasy schema mirrors
CREATE TABLE IF NOT EXISTS fantasy.games (LIKE public.games INCLUDING ALL);
CREATE TABLE IF NOT EXISTS fantasy.teams (LIKE public.teams INCLUDING ALL);
CREATE TABLE IF NOT EXISTS fantasy.team_boxscores_home_batting (LIKE public.team_boxscores_home_batting INCLUDING ALL);
CREATE TABLE IF NOT EXISTS fantasy.team_boxscores_away_batting (LIKE public.team_boxscores_away_batting INCLUDING ALL);
CREATE TABLE IF NOT EXISTS fantasy.team_boxscores_home_pitching_and_fielding (LIKE public.team_boxscores_home_pitching_and_fielding INCLUDING ALL);
CREATE TABLE IF NOT EXISTS fantasy.team_boxscores_away_pitching_and_fielding (LIKE public.team_boxscores_away_pitching_and_fielding INCLUDING ALL);
CREATE TABLE IF NOT EXISTS fantasy.player_batting (LIKE public.player_batting INCLUDING ALL);
CREATE TABLE IF NOT EXISTS fantasy.player_pitching (LIKE public.player_pitching INCLUDING ALL);
CREATE TABLE IF NOT EXISTS fantasy.player_fielding (LIKE public.player_fielding INCLUDING ALL);
