create table player_season_pitching
(
    player_team_season_id    text not null,
    player_id                int  not null,
    season                   int  not null,
    name                     text,
    link                     text,
    team_id                  int  not null,
    starts                   int,
    appearances              int,
    flyouts                  int,
    groundouts               int,
    airouts                  int,
    runs                     int,
    rbi                      int,
    singles                  int,
    doubles                  int,
    triples                  int,
    homeruns                 int,
    strikeouts               int,
    walks                    int,
    intentional_walks        int,
    hits                     int,
    hbp                      int,
    at_bats                  int,
    avg                      numeric,
    obp                      numeric,
    slg                      numeric,
    ops                      numeric,
    iso                      numeric,
    caught_stealing          int,
    stolen_bases             int,
    ip                       numeric,
    wins                     int,
    losses                   int,
    saves                    int,
    save_opportunities       int,
    holds                    int,
    blown_saves              int,
    earned_runs              int,
    batters_faced            int,
    outs                     int,
    complete_games           int,
    shutouts                 int,
    pitch_count              int,
    balls                    int,
    strikes                  int,
    balks                    int,
    wild_pitches             int,
    pickoffs                 int,
    runs_per_9               numeric,
    homeruns_per_9           numeric,
    inherited_runners        int,
    inherited_runners_scored int,
    catchers_int             int,
    sac_bunts                int,
    sac_flies                int,
    passed_ball              int,
    popouts                  int,
    lineouts                 int,
    era numeric,
    whip numeric,
    k_per_9 numeric,
    bb_per_9 numeric,
    k_perc numeric,
    bb_perc numeric,
    k_per_minus_bb_perc numeric,
    babip numeric
)