create table player_season_batting
(
    player_id int not null,
    season    int not null,
    games int,
    flyouts int,
    groundouts int,
    airouts int,
    runs int,
    rbi int,
    singles int,
    doubles int,
    triples int,
    homeruns int,
    strikeouts int,
    walks int,
    intentional_walks int,
    hits int,
    hbp int,
    at_bats int,
    plate_appearances int,
    avg numeric,
    obp numeric,
    slg numeric,
    iso numeric,
    ops numeric,
    bb_perc numeric,
    k_perc numeric,
    bb_per_k numeric,
    babip numeric,
    caught_stealing int,
    stolen_bases int,
    gidp int,
    gitp int,
    total_bases int,
    lob int,
    sac_bunts int,
    sac_flies int,
    catchers_int int,
    pickoffs int,
    popouts int,
    lineouts int,
    updated_at timestamptz default now(),
    primary key (player_id, season)
)